# python3 -m http.server
# http://localhost:8000/

# python3 http.server documentation:    https://docs.python.org/3/library/http.server.html
# create web server instructions / info:    https://pythonbasics.org/webserver/

from http.server import BaseHTTPRequestHandler, HTTPServer
import http.server
import socketserver
import time

#####
HOST = "localhost"       # host for development
PORT = 8000              # port 8000: used for development, shouldn't be directly exposed to internet

Handler = http.server.SimpleHTTPRequestHandler
#####

### create web server
class DtsServer (BaseHTTPRequestHandler):       # class used for creating server
    # if request mapped to a dir, dir is checked for file "index.html".
        # if found, file contents are returned.
        # else, dir listing is generated by calling list_directory() -- method uses os.listdir() to scan dir
    def do_GET (self):                         
        self.send_response(200)
        self.send_header("Content-type", "text/html")
        self.end_headers()
        self.wfile.write(bytes("<html><head><title>hhhhjjhjhhhhh</title></head>", "utf-8"))
        #self.wfile.write(bytes("<p>ur mom</p>", "utf-8"))
        #self.wfile.write(bytes("<p>Request: %s</p>" % self.path, "utf-8"))
        self.wfile.write(bytes("<body>", "utf-8"))
        self.wfile.write(bytes("<p>stuff</p>", "utf-8"))


### create simple web server for serving files relative to current dir
def simple_server (Handler=Handler, HOST=HOST, PORT=PORT):          
    with socketserver.TCPServer((HOST, PORT), Handler) as httpd:
        print("serving at port", PORT)
        httpd.serve_forever()


#####
if __name__ == "__main__":        
    webServer = HTTPServer((HOST, PORT), DtsServer)             # builds on TCPServer class, stores server address as instance variables
    print(f"Server started http://{HOST}:{PORT}")               # print server address to terminal

    try:
        webServer.serve_forever()
    except KeyboardInterrupt:
        pass
    

    webServer.server_close()
    print("Server stopped.")
